
import java.util.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jirawan
 */
public class Lobby extends javax.swing.JFrame {

    /**
     * Creates new form Lobby
     */
    public Lobby() {
        initComponents();
        LobbyDB db1 = new LobbyDB();
        Lobbyservice.showList(listname, listunit);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listname = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listunit = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        profilebtn = new javax.swing.JButton();
        createroombtn = new javax.swing.JButton();
        leaderboardbtn = new javax.swing.JButton();
        onlineplayerbyn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        testfield = new javax.swing.JTextField();

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Netbean\\OXProjects\\src\\Image\\bg.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oxgame");
        setMaximumSize(new java.awt.Dimension(605, 429));
        setMinimumSize(new java.awt.Dimension(605, 429));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(listname);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, -1));

        listunit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listunit.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listunit.setEnabled(false);
        jScrollPane3.setViewportView(listunit);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 60, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Unit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Netbean\\OXProjects\\src\\Image\\picture.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 110, 130));

        profilebtn.setBackground(new java.awt.Color(0, 153, 153));
        profilebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        profilebtn.setText("Profile");
        profilebtn.setBorder(null);
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });
        getContentPane().add(profilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 182, 65, 30));

        createroombtn.setBackground(new java.awt.Color(0, 153, 153));
        createroombtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createroombtn.setText("CreateRoom");
        createroombtn.setBorder(null);
        createroombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createroombtnActionPerformed(evt);
            }
        });
        getContentPane().add(createroombtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 99, 29));

        leaderboardbtn.setBackground(new java.awt.Color(0, 153, 153));
        leaderboardbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        leaderboardbtn.setText("LeaderBoard");
        leaderboardbtn.setBorder(null);
        leaderboardbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboardbtnActionPerformed(evt);
            }
        });
        getContentPane().add(leaderboardbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 160, 30));

        onlineplayerbyn.setBackground(new java.awt.Color(0, 153, 153));
        onlineplayerbyn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        onlineplayerbyn.setText("Online");
        onlineplayerbyn.setBorder(null);
        onlineplayerbyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineplayerbynActionPerformed(evt);
            }
        });
        getContentPane().add(onlineplayerbyn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 100, 26));

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.setBorder(null);
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 60, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Created by Sec3 Gruop 4");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("L O B B Y");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 210, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Netbean\\OXProjects\\src\\Image\\bg.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        testfield.setEditable(false);
        getContentPane().add(testfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 110, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebtnActionPerformed
        Profile pf = new  Profile();
        pf.show();
        
        this.hide();
        
    }//GEN-LAST:event_profilebtnActionPerformed

    private void createroombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createroombtnActionPerformed
        // TODO add your handling code here:
        CreateRoomGUI croom = new  CreateRoomGUI();
        croom.show();
        
        
    }//GEN-LAST:event_createroombtnActionPerformed

    private void leaderboardbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardbtnActionPerformed
        // TODO add your handling code here:
        LeaderBoard lboard = new  LeaderBoard();
        lboard.show();
        
        
       
    }//GEN-LAST:event_leaderboardbtnActionPerformed

    private void onlineplayerbynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineplayerbynActionPerformed
        // TODO add your handling code here:
        OnlinePlayer onl= new  OnlinePlayer();
        onl.show();
        
        
    }//GEN-LAST:event_onlineplayerbynActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Login login = new Login();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lobby().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton createroombtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton leaderboardbtn;
    private static javax.swing.JList<String> listname;
    public static javax.swing.JList<String> listunit;
    private javax.swing.JButton onlineplayerbyn;
    private javax.swing.JButton profilebtn;
    public static javax.swing.JTextField testfield;
    // End of variables declaration//GEN-END:variables
}
